[button]
back = "â¬… å›åˆ°é¦–é¡µ"
start_bind = "ğŸ”’ ç»‘å®šè´¦å·"
start_unbind = "ğŸ”“ è§£ç»‘è´¦å·"
start_export = "ğŸ“¤ å¯¼å‡ºè´¦å·"
start_import = "ğŸ“¥ å¯¼å…¥è´¦å·"
start_my = "ğŸ§‘ æˆ‘çš„ä¿¡æ¯"
start_settings = "âš™ è®¾ç½®"

settings_language = "ğŸŒ è¯­è¨€"

[start]
desc = """
âœ¨ ä½ å¥½ï¼[{{ .Username }}](tg://user?id={{ .ID }}) âœ¨

*E5SubBot æ˜¯ä¸“æ³¨äºç®€åŒ–E5ç»­è®¢çš„ Bot*

[GitHub](https://github.com/iyear/E5SubBot) | [å®˜æ–¹ç¾¤ç»„](https://t.me/e5subbot)

**å…¬å‘Š:** ```{{ .Notice }}```
ğŸ‘‡ ç‚¹å‡»æŒ‰é’®å¼€å§‹ä½¿ç”¨ ğŸ‘‡
"""

[settings]
desc = "ğŸ‘‡ è¯·é€‰æ‹©ä½ çš„è®¾ç½®é¡¹"
language = """
ğŸŒ å½“å‰è¯­è¨€ä¸º: *{{ . }}*

ğŸ‘‡ è¯·é€‰æ‹©éœ€è¦è®¾ç½®çš„è¯­è¨€
"""

[my]
desc = """
âœ¨ é€‰æ‹©ä¸€ä¸ªè´¦æˆ·æŸ¥çœ‹å…·ä½“ä¿¡æ¯

ç»‘å®šæ•°: `{{ .Current }}`/`{{ .BindMax }}`
"""