[button]
back = "â¬… å›åˆ°é¦–é¡µ"
start_bind = "ğŸ”’ ç»‘å®šè´¦å·"
start_unbind = "ğŸ”“ è§£ç»‘è´¦å·"
start_export = "ğŸ“¤ å¯¼å‡ºè´¦å·"
start_import = "ğŸ“¥ å¯¼å…¥è´¦å·"
start_my = "ğŸ§‘ æˆ‘çš„ä¿¡æ¯"
start_help = "ğŸ“– å¸®åŠ©"

[start]
desc = """
âœ¨ ä½ å¥½ï¼[{{ .Username }}](tg://user?id={{ .ID }}) âœ¨

*PayInBot æ˜¯ä¸“æ³¨äºç®€åŒ–ä»˜è´¹å…¥ç¾¤æµç¨‹çš„ Bot*

[GitHub](https://github.com/iyear/E5SubBot) | [Chat](https://t.me/e5subbot)

**å…¬å‘Š:** ```{{ .Notice }}```
ğŸ‘‡ ç‚¹å‡»æŒ‰é’®å¼€å§‹ä½¿ç”¨ ğŸ‘‡
"""